#!/bin/bash

#
# This scripts helps to test the parsing of the full COSMO
# code by the OMNI Compiler.
#

function show_help(){
  echo "$0 [-b <branch-name>] [-s] [-c] [-p] [-o]"
  echo ""
  echo "Options:"
  echo " -b <branch-name>  Specifiy which CLAW branch to be used for the test"
#  echo " -f                Use the forked repository for test"
#  echo " -c <compiler-id>  Define the base compiler to use"
#  echo " -i <install-path> Set an install path"

  echo " -s                Skip CLAW/OMNI compilation/install"
  echo " -r                Test cosmo-prerelease instead of cosmo-pompa"
  echo " -c                Skip fetching step for COSMO"
  echo " -p                Skip parsing step"
  echo " -o                Use the latest OMNI Compiler version for the test"
  echo " -n                Test with NETCDF enabled"
}

source ./common/utility.sh
source ./common/omni.lib.sh

# Working directories for the test
TEST_DIR=${PWD}/build
CLAW_OUTPUT="./processed/cosmo"
XMOD_DIR="./xmods/cosmo"
EXTERNAL_XMODS="../cosmo/external_xmods"
GLOBAL_XMODS="../global_modules"

# CLAW repository variables
CLAW_BRANCH="master"
CLAW_MAIN_REPO="https://github.com/claw-project/claw-compiler.git"
CLAW_REPO=${CLAW_MAIN_REPO}
CLAWFC=./claw/bin/clawfc

# Default compiler used
BASE_COMPILER="gnu"

# Option switches
SKIP_CLAW=false
SKIP_FETCH=false
SKIP_PARSING=false
OMNI_LATEST=false
NETCDF_ENABLE=false
PRERELEASE=false


# This to avoid the outside OpenACC problem
# COSMO_DEFINITIONS+=" -DPGI_FIX_ACCROUTINE_PLACEMENT"

# Parsing output
PARSING_OUTPUT=${TEST_DIR}/cosmo_parse_test.log

while getopts "hb:csponr" opt; do
  case "$opt" in
  h)
    show_help
    exit 0
    ;;
  s) SKIP_CLAW=true ;;
  p) SKIP_PARSING=true ;;
  c) SKIP_FETCH=true ;;
  o) OMNI_LATEST=true ;;
  b) CLAW_BRANCH=$OPTARG ;;
  n) NETCDF_ENABLE=true ;;
  r) PRERELEASE=true ;;
  *)
     show_help
     exit 1
     ;;
  esac
done

if [[ ${PRERELEASE} == true ]]; then
  COSMO_VERSION="COSMO-PRERELEASE"
  COSMO_MAIN_REPO="git@github.com:MeteoSwiss-APN/cosmo-prerelease.git"
  COSMO_REP="cosmo-prerelease"
  COSMO_SRC="./${COSMO_REP}/cosmo/src/"
  COSMO_START="lmorg.f90"
  COSMO_DEP="dependencies_cosmo"
  COSMO_EXCLUDED_FILES="test_src_lbc.f90:cosmo_ppser.f90"
  COSMO_NETCDF_INC="${COSMO_SRC}/../include/netcdf/"

  COSMO_DEFINITIONS="-D__CRAY_FORTRAN__ -DHAS_IOMSG -DCRAY_FIX_WKARR"
  COSMO_DEFINITIONS+=" -DCRAY_FIX_PARALLEL_OPTIONAL_LOGICAL -DIEEE_INTR"
  COSMO_DEFINITIONS+=" -D_LOC_TIMING -DGSP_FIRST -DNUDGING -DCPP_DYCORE"
  COSMO_DEFINITIONS+=" -DGCL_COMM -DGRIBDWD -DGRIBAPI -D_OPENACC -D__COSMO__"
  COSMO_DEFINITIONS+=" -DPGI_FIX_ACCROUTINE_PLACEMENT -DCRAY_FIX_REALLOC -DALLOC_WKARR"
else
  COSMO_VERSION="COSMO-POMPA"
  COSMO_MAIN_REPO="git@github.com:MeteoSwiss-APN/cosmo-pompa.git"
  COSMO_REP="cosmo-pompa"
  COSMO_SRC="./${COSMO_REP}/cosmo/src/"
  COSMO_START="lmorg.f90"
  COSMO_DEP="dependencies_cosmo"
  COSMO_EXCLUDED_FILES="test_src_lbc.f90:cosmo_ppser.f90"
  COSMO_NETCDF_INC="${COSMO_SRC}/../include/netcdf/"

  COSMO_DEFINITIONS="-D__CRAY_FORTRAN__ -DHAS_IOMSG -DCRAY_FIX_WKARR"
  COSMO_DEFINITIONS+=" -DCRAY_FIX_PARALLEL_OPTIONAL_LOGICAL -DIEEE_INTR"
  COSMO_DEFINITIONS+=" -D_LOC_TIMING -DGSP_FIRST -DNUDGING -DPOLLEN -DCPP_DYCORE"
  COSMO_DEFINITIONS+=" -DGCL_COMM -DGRIBDWD -DGRIBAPI -D_OPENACC -D__COSMO__"
  COSMO_DEFINITIONS+=" -DPGI_FIX_ACCROUTINE_PLACEMENT -DCRAY_FIX_REALLOC"
fi

if [[ ${OMNI_LATEST} == true ]] && [[ ${SKIP_CLAW} == true ]]; then
  echo "Incompatible options -o and -s ..."
  exit 1
fi

if [[ ${NETCDF_ENABLE} == true ]]; then
  COSMO_DEFINITIONS+=" -DNETCDF"
  COSMO_EXCLUDED_FILES="${COSMO_EXCLUDED_FILES}:dummy_netcdf.f90"
fi

COMPUTER=$(hostname)

#if [[ $COMPUTER == *"daint"* ]]
#then
#  COMPUTER="daint"
#  CMAKE_MOD="CMake"
if [[ ${COMPUTER} == *"kesch"* ]]; then
  COMPUTER="kesch"
fi

# Try to load machine specific compiler information
COMPILER_FILE="./compiler/${COMPUTER}.${BASE_COMPILER}.sh"
if [ -f ${COMPILER_FILE} ]; then
  # shellcheck source=./compiler/clementon2.gnu.sh
  source ${COMPILER_FILE}
else
  echo "Warning: Compiler file $COMPILER_FILE missing. Default values are used."
fi

#
#
#
## Load recent version of cmake
#module load $CMAKE_MOD
#
## Load correct PrgEnv
#case  "$CLAW_BASE_COMPILER" in
#  "gnu")
#    module rm PrgEnv-pgi && module rm PrgEnv-cray
#    module load PrgEnv-gnu
#    if [[ $COMPUTER == "kesch" ]]
#    then
#      CLAW_FC=gfortran
#      CLAW_CC=gcc
#      CLAW_CXX=g++
#    elif [[ $COMPUTER == "daint" ]]
#    then
#      CLAW_FC=ftn
#      CLAW_CC=cc
#      CLAW_CXX=CC
#      OMNI_MPI_CC="MPI_CC=cc"
#      OMNI_MPI_FC="MPI_FC=ftn"
#      ADDITONAL_OPTIONS="-DOMNI_MPI_CC=$OMNI_MPI_CC -DOMNI_MPI_FC=$OMNI_MPI_FC"
#    fi
#  ;;
#  "pgi")
#    module rm PrgEnv-gnu && module rm PrgEnv-cray
#    module load PrgEnv-pgi
#    if [[ $COMPUTER == "kesch" ]]
#    then
#      CLAW_FC=mpif90
#      CLAW_CC=mpicc
#      CLAW_CXX=pgc++
#    elif [[ $COMPUTER == "daint" ]]
#    then
#      module load gcc
#      CLAW_FC=ftn
#      CLAW_CC=cc
#      CLAW_CXX=CC
#      OMNI_MPI_CC="MPI_CC=cc"
#      OMNI_MPI_FC="MPI_FC=ftn"
#      ADDITONAL_OPTIONS="-DOMNI_MPI_CC=$OMNI_MPI_CC -DOMNI_MPI_FC=$OMNI_MPI_FC"
#    fi
#  ;;
#  "cray")
#    module rm PrgEnv-pgi && module rm PrgEnv-gnu
#    module load PrgEnv-cray
#    CLAW_FC=ftn
#    CLAW_CC=cc
#    CLAW_CXX=CC
#  ;;
#  *)
#    echo "Error: Unknown compiler ..."
#    exit 1
#esac

echo ""
echo "============================================"
echo "${COSMO_VERSION} -> CLAW/OMNI Compiler parse test"
echo "============================================"
echo "- COMSO information"
echo "  - Git repository: $COSMO_MAIN_REPO"

# Fetch the submodules
git submodule init
if [[ ${OMNI_LATEST} == true ]]; then
  echo "- OMNI fetch latest commit from submodule!"
  git submodule update --remote
else
  git submodule update
fi

if [[ ${SKIP_CLAW} == false ]]; then
  # Specific CLAW/OMNI information
  echo "- CLAW Compiler information:"
  echo "  - Git repository: ${CLAW_REPO}"
  echo "  - Git branch: ${CLAW_BRANCH}"
  echo "  - Base compiler: ${BASE_COMPILER}"
  echo "  - Target directory: ${TEST_DIR}"

  rm -rf "${TEST_DIR}"
  mkdir "${TEST_DIR}"

  ###############################
  # 1. CLAW FORTRAN Compiler step
  ###############################

  print_green "[INFO] CLAW FORTRAN COMPILER STEP: Clone and compile"
  if [[ ${OMNI_LATEST} == true ]]; then
    ./common/compile.claw -d "${TEST_DIR}" -c "${BASE_COMPILER}" -r "${CLAW_REPO}" -b "${CLAW_BRANCH}" -o
  else
    ./common/compile.claw -d "${TEST_DIR}" -c "${BASE_COMPILER}" -r "${CLAW_REPO}" -b "${CLAW_BRANCH}"
  fi
elif [[ ${SKIP_FETCH} == false ]]; then
  rm -rf "${TEST_DIR:?}"/${COSMO_REP}
fi

echo "============================================"
echo ""


cd "${TEST_DIR}" || exit 1
WORKING_DIR="$PWD"

# Get git hashes for the log
cd claw-compiler || exit 1
CLAW_HASH=$(git rev-parse HEAD)
cd omni-compiler || exit 1
OMNI_HASH=$(git rev-parse HEAD)
cd "${WORKING_DIR}" || exit 1


if [[ ${SKIP_FETCH} == false ]]; then
  #####################
  # 2. COSMO step
  #####################
  print_green "[INFO] Fetching ${COSMO_VERSION}"
  git clone ${COSMO_MAIN_REPO}
fi

cd ${COSMO_REP} || exit 1
COSMO_HASH=$(git rev-parse HEAD)
cd "${WORKING_DIR}" || exit 1

if [[ ${SKIP_PARSING} == false ]]; then
{
  echo "COSMO PARSING TESTS"
  echo "-------------------"
  echo "Git version information:"
  echo "- CLAW git version: ${CLAW_HASH}"
  echo "- OMNI git version: ${OMNI_HASH}"
  echo "- ${COSMO_VERSION} git version: ${COSMO_HASH}"
} > "${PARSING_OUTPUT}"

  ####################
  # 3. Dependency step
  ####################

  # Generate the dependency list for the parsing order
  print_green "[INFO] Generate dependencies list"
  echo "../fdependencies/generate_dep.py ${COSMO_SRC} ${COSMO_START} --exclude ${COSMO_EXCLUDED_FILES} > ${COSMO_DEP} 2> dependencies_cosmo.out" >> "${PARSING_OUTPUT}"
  ../fdependencies/generate_dep.py ${COSMO_SRC} ${COSMO_START} --exclude ${COSMO_EXCLUDED_FILES} > ${COSMO_DEP} 2> dependencies_cosmo.out
  echo "   ${COSMO_DEP}"

  # Check existence of the dependencies file
  if [[ ! -f ${COSMO_DEP} ]]; then
    echo "ERROR: ${COSMO_DEP} does not exists!"
    exit 1
  fi

  if [[ $(wc -l < ${COSMO_DEP}) -lt 2 ]]; then
    echo "ERROR: ${COSMO_DEP} is empty!"
    exit 1
  fi


  #################
  # 4. Parsing step
  #################

  # Check existence of the CLAW FORTRAN Compiler
  if [[ ! -f ${CLAWFC} ]]; then
    echo "ERROR: ${CLAWFC} does not exists!"
    exit 1
  fi

  mkdir -p ${XMOD_DIR}
  mkdir -p ${CLAW_OUTPUT}

  # Clean-up directories of potential previous run
  rm "${CLAW_OUTPUT}"/*.f90
  rm "${XMOD_DIR}"/*.xmod

  parsed_files=0
  print_green "[INFO] Parsing files"
  echo "" >> "${PARSING_OUTPUT}"
  echo "Parsing files:" >> "${PARSING_OUTPUT}"
  while IFS= read -r f90_file; do
    echo "    Processing file ${COSMO_SRC}${f90_file} -> ${CLAW_OUTPUT}/${f90_file}"
    echo "    Processing file ${COSMO_SRC}${f90_file} -> ${CLAW_OUTPUT}/${f90_file}" >> "${PARSING_OUTPUT}"
    mkdir -p "$(dirname "${CLAW_OUTPUT}"/"${f90_file}")"
    echo "cmd: ${CLAWFC} ${COSMO_DEFINITIONS} --no-dep --debug-omni -J ${XMOD_DIR} -J ${GLOBAL_XMODS} -J ${EXTERNAL_XMODS} --force -I ${INCLUDE_MPI} -I ${COSMO_NETCDF_INC} -I ${COSMO_SRC} -o ${CLAW_OUTPUT}/${f90_file} ${COSMO_SRC}${f90_file}" >> "${PARSING_OUTPUT}" 2>&1
    ${CLAWFC} "${COSMO_DEFINITIONS}" --no-dep --debug-omni -J ${XMOD_DIR} -J ${GLOBAL_XMODS} -J ${EXTERNAL_XMODS} --force -I "${INCLUDE_MPI}" -I "${COSMO_NETCDF_INC}" -I "${COSMO_SRC}" -o "${CLAW_OUTPUT}"/"${f90_file}" "${COSMO_SRC}""${f90_file}" >> "${PARSING_OUTPUT}" 2>&1
    (( parsed_files=parsed_files+1 ))
    if [[ ! -f ${CLAW_OUTPUT}/${f90_file} ]]; then
      print_red "[FAILED] ""${COSMO_SRC}""${f90_file}"
    fi
  done < ./${COSMO_DEP}
fi


#################
# 5. Control step
#################

# Control if present .xmod file has been produced correctly
omni::check_xmod ${XMOD_DIR} xmod_errors

# Control output fortran file any corruption
omni::check_fortran ${COSMO_DEP} ${CLAW_OUTPUT} f90_errors

echo ""
echo "====================================="
echo "${COSMO_VERSION} full parsing test results"
echo "====================================="

# shellcheck disable=SC2154
if [[ ${xmod_errors} -ne 0 ]] || [[ ${f90_errors} -ne 0 ]]; then
  # Check potential known errors in log file
  omni::check_error_log "${PARSING_OUTPUT}"
  print_red "FAILED: Parsing test has detected some errors."
  exit 1
else
  print_green "SUCCESS: Test has be executed correctly."
  echo "================================"
  exit 0
fi
